# Generated by Django 5.0 on 2023-12-06 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_agendamento_hora_alter_agendamento_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='data',
            field=models.CharField(max_length=50),
        ),
    ]
